sudo: required
services:
- docker
before_script:
- yarn
script: yarn coverage
language: node_js
env:
- PORT=8099
node_js:
- '8'
after_success:
#todo: make sure build fails if dependencies failed to install
- yarn --production
- docker-compose build
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push domrevigor/domrevigor:advanced-react
- docker tag domrevigor/domrevigor:advanced-react registry.heroku.com/advanced-react-course/web
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh 
- heroku container:login
- docker push registry.heroku.com/advanced-react-course/web
