sudo: required
services:
- docker
before_script:
- echo ${HOST}
- yarn
script: yarn coverage
language: node_js
env:
- PORT=8099 HOST=${HOST}
node_js:
- '8'
after_success:
#todo: make sure build fails if dependencies failed to install
# - docker-compose build
- docker build -t domrevigor/domrevigor:advanced-react --build-arg mongoHost=${mongoHost} --build-arg mongoPort=${mongoPort} --build-arg mongoUser=${mongoUser} --build-arg mongoPass=${mongoPass} .
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push domrevigor/domrevigor:advanced-react
- docker tag domrevigor/domrevigor:advanced-react registry.heroku.com/advanced-react-course/web
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh 
- heroku container:login
- docker push registry.heroku.com/advanced-react-course/web
